### ISSUE TITLE
Is it time to tag a new release?

### ISSUE THREAD

**Issue by thaJeztah** [containerd/typeurl#23]
I noticed this repository tagged a v1.0.0 release, but after that added a `go.mod`, and various other changes;

https://github.com/containerd/typeurl/compare/v1.0.0...cd3ce7159eae562a4f60ceff37dada11a939d247

wondering if there's plans to tag a new release, or if other changes are still in the pipeline

(came here, because I noticed BuildKit is using a version from master, and because of that moby/moby as well)

@mxpv @estesp @crosbymichael @tonistiigi

**Comment by crosbymichael** [comment]
we can tag if a commit makes sense.  will this be a 1.1 or a 1.0.1?

**Comment by thaJeztah** [comment]
I think I see some new functions were added, so I guess it would be 1.1.0 (minor should be updated for new features).

It's not super urgent (as in: if we know things are in the pipeline, feel free to wait for those)

**Comment by AkihiroSuda** [comment]
https://github.com/containerd/typeurl/releases/tag/v1.0.2
