### ISSUE TITLE
Copyright is missing

### ISSUE THREAD

**Issue by elboulangero** [containerd/typeurl#4]
Dear containerd authors,

I would like to package this library for Debian, however I couldn't find a copyright anywhere. This should be mentioned in the LICENSE file as well, right now the copyright line there is just a template.

https://github.com/containerd/typeurl/blob/f6943554a7e7e88b3c14aad190bf05932da84788/LICENSE#L189

Thanks

**Comment by estesp** [comment]
This looks resolved.
